// Generated by https://quicktype.io

export interface NowPlaying {
  page:          number;
  results:       Movie[];
  dates:         Dates;
  total_pages:   number;
  total_moviess: number;
}

export interface Dates {
  maximum: string;
  minimum: string;
}

export interface Movie {
  poster_path:       string;
  adult:             boolean;
  overview:          string;
  release_date:      string;
  genre_ids:         number[];
  id:                number;
  original_title:    string;
  original_language: OriginalLanguage;
  title:             string;
  backdrop_path:     string;
  popularity:        number;
  vote_count:        number;
  video:             boolean;
  vote_average:      number;
}

export enum OriginalLanguage {
  En = "en",
  Sv = "sv",
}
