// Generated by https://quicktype.io

import { Movie } from "./NowPlayingInterface";


export interface SearchMovie {
  page:          number;
  results:       Movie[];
  total_results: number;
  total_pages:   number;
}


export enum OriginalLanguage {
  En = "en",
  It = "it",
  Zh = "zh",
}
